name: Puzzles HQ workflow

on:
  release:
    types: [published]

jobs:
  publish-release:
    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/maven-puzzle-publishing.yml@main
    secrets: inherit
